- name: create new user
  ansible.builtin.user:
    name: "{{ newuser }}"
    password_expire_max: 1
    group: "example-group"
    create_home: true
    password: "{{ 'admin' | password_hash('sha512','hahaha') }}"
    state: "present"
    shell: "/bin/bash"
    system: false
