---
- name: test ping command
  hosts: all
  tasks:
    - name: ping
      ping: 
- name: new group
  hosts: all
  become: true
  vars:
    newgroup: example-group
  tasks: 
    - name: create new group
      ansible.builtin.group:
        name: "{{ newgroup }}"
        system: true
- name: new user
  hosts: all
  become: true
  vars:
    newuser: example-user
  tasks: 
    - name: create new user
      ansible.builtin.user:
        name: "{{ newuser }}"
        password_expire_min: 1
        group: "example-group"
        create_home: true
        password: "{{ 'admin' | password_hash('sha512','hahaha') }}"
        state: "present"
        shell: "/bin/bash"
        system: false


